export {default as Navbar} from './navbar/Navbar'
export {default as Service} from './service/Service'
export {default as WhyComponent} from './whyComponent/WhyComponent'
export {default as Method} from './methodComponent/MethodComponent'
export {default as Header} from "./headerComponent/HeaderComponent"
export {default as HeaderImage} from "./headerImage/HeaderImage"
export {default as NewsComponent} from "./newsComponent/NewsComponent"
export {default as NewsPageComponent} from "./newsPageComponent/NewsPageComponent"
export {default as TeamComponent} from "./teamComponent/TeamComponent"